# Generated by Django 5.0 on 2024-01-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajachica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoscajachica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
