# Generated by Django 5.0 on 2024-01-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajachica', '0002_alter_movimientoscajachica_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasCajaChica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
