# Generated by Django 5.0 on 2024-01-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajachica', '0003_notascajachica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoscajachica',
            name='motivo',
            field=models.CharField(max_length=400),
        ),
    ]
