# Generated by Django 5.0 on 2024-01-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajachica', '0005_alter_movimientoscajachica_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notascajachica',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notascajachica',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
