# Generated by Django 5.0 on 2024-01-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=50)),
                ('vendedor', models.CharField(max_length=50)),
                ('distribucion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
