# Generated by Django 5.0 on 2024-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_rename_serie_ventas_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='saldo_pendiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
