# Generated by Django 5.0 on 2024-01-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_ventas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
