# Generated by Django 5.0 on 2024-01-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_ventas_fecha_pago'),
    ]

    operations = [
    ]
