# Generated by Django 5.0 on 2024-01-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_ventas_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
