# Generated by Django 5.0 on 2024-01-19 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_ventas_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha_pago',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
