# Generated by Django 5.0 on 2024-01-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_ventas_fecha_alter_ventas_fecha_pago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
