# Generated by Django 5.0 on 2023-12-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculos_año_alter_vehiculos_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculos',
            name='marca',
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
