# Generated by Django 5.0 on 2024-01-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_vehiculos_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='conductor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
