# Generated by Django 5.0 on 2024-01-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_tenencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenencia',
            new_name='Tenencias',
        ),
    ]
