# Generated by Django 5.0 on 2024-01-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasVehiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=500)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
